WIP Common - Add taric and ekko documentation for spring 2
intellisys/Runaterra-Docs pull request #7
Opened 2017-05-25 20:00 UTC by Eduardoveras

WIP, dont merge

2017-06-02 18:07 UTC, jvinas requested changes

2017-06-02 18:07 UTC, jvinas commented on Service-Access.md
> +# Accesing the services
These informations should be placed in wiki page of the project .. check the table that exists in there

2017-06-07 14:15 UTC, Eduardoveras commented
@jvinas please review again

2017-06-08 20:29 UTC, jvinas approved these changes

2017-06-13 18:51 UTC, merged